[profile.default]
src = 'contracts'
test = 'test/forge'
libs = ['node_modules', 'lib']
out = 'out'
cache_path  = 'forge-cache'
verbosity = 2
# comment out if you notice any weird behavior
#sparse_mode = true

# See more config options https://book.getfoundry.sh/reference/config.html