name: Solidity CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install
      - run: npx hardhat compile --show-stack-traces
      - run: TS_NODE_TRANSPILE_ONLY=1 npx hardhat test --parallel
  forge_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Node modules
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install
      - name: Run tests
        run: FOUNDRY_PROFILE=intense forge test -vvv --no-match-contract=ValidatorStorage && forge test -vvv match-contract=ValidatorStorage
  gas_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install
      - run: TS_NODE_TRANSPILE_ONLY=1 npx hardhat test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install
      - run: npx solhint "contracts/**/*.sol"
      - run: npx eslint .
      - run: npx prettier -c .
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: crytic/slither-action@v0.1.1
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install
      - run: npx hardhat compile
      - name: solidity-coverage
        run: npx hardhat coverage
      - name: coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
